### PR TITLE
Update go-cam-shapes.shex

### PR DESCRIPTION
**Pull request by vanaukenk**
Adding BP relations as per discussions with @thomaspd and on GO-CAM specs calls.  

Still need to confirm that the ranges and cardinalities are correct for each.  

Also, do we need to update CellularComponent to CellularAnatomicalEntity for some or all entries?

@goodb - please also add any other relations that are needed for the Reactome imports.  Thx.

### CODE REVIEW

**Comment by vanaukenk** [comment]
@balhoff 

It looks like the model in the 'should pass' directory that is actually failing is this one:

http://noctua.geneontology.org/editor/graph/gomodel:5c4605cc00003994

Could this possibly be due to the use of the ZFA identifier for 'neuronal stem cell':

http://purl.obolibrary.org/obo/ZFA_0009019

instead of the CL term?

http://purl.obolibrary.org/obo/CL_0000047

**Comment by goodb** [comment]
@vanaukenk Yes.  If you replace http://purl.obolibrary.org/obo/ZFA_0009019
with http://purl.obolibrary.org/obo/CL_0000047 on the instance node: http://model.geneontology.org/5c4605cc00003994/5c4605cc00004005 the test will pass.  

But, this seems like it might be a weakness of the testing environment, not necessarily the model or the schema.  Isn't the idea that ZFA term is a subclass of http://purl.obolibrary.org/obo/CARO_0000000 ?  Right now, that connection is not present in the class graph used by the test validator http://rdf.geneontology.org/blazegraph/

**Comment by vanaukenk** [comment]
@goodb  Yes, I agree.  

I thought that http://purl.obolibrary.org/obo/ZFA_0009019 would be recognized as a http://purl.obolibrary.org/obo/CARO_0000000 but it looks like we don't have that information yet.

**Comment by goodb** [comment]
Its the same problem for other species specific anatomy ontology terms like http://purl.obolibrary.org/obo/FBbt_00100504  .  
I think there is a ticket somewhere related to the upper-level anatomy and relation to cell component, but not finding it anywhere.  There is also this one which could solve it https://github.com/geneontology/go-ontology/issues/12221

**Comment by balhoff** [comment]
This should be covered by the fairly recent change to pre-reason go-lego before release. If connections are missing, then either:
- we need to add bridge axioms (very likely)
- it could be a mouse term (can't pre-reason the EMAPA terms due to logical incompatibilities) - *not the problem with this one of course*
- triplestore may be out of date?

**Comment by goodb** [comment]
@balhoff I set things up so I can run the shex validation with locally loaded ontologies (same as in Minerva).  Couple things.  

1) Using the merged go-lego at http://purl.obolibrary.org/obo/go/extensions/go-lego.owl we still have the same problem.  I think we are missing the bridging axioms.  

2) Thoughts on changing the test here so its dependent on loading go-lego.owl rather than hitting rdf.geneontology.org ?  It is slower (188 seconds when go-lego is read from a local file versus 9 seconds when hitting the remote sparql service) and more memory intensive (due to the size of go-lego).  But, it acts more predictably like what is running now in Minerva and won't be subject to unpredictable lags in the update of rdf.go 

?

**Comment by balhoff** [comment]
That seems like a good idea. Better than having the tests rely on an external service. However ideally it would be committed to the repo. I expect it's too big for that.

**Comment by goodb** [comment]
@vanaukenk Jim thinks the ontology changes may take some time.  To avoid delays here, I went ahead and changed the offending zfa term to cell ontology term. https://github.com/geneontology/go-shapes/pull/160/commits/e9d75dcd21639db8591c3a62f6fedd991bab78b0  If that is okay with you, we can merge to master and move on.

**Comment by vanaukenk** [comment]
Thanks @goodb 
I think this makes sense for now, but will discuss with Sabrina Toro next week so the Zfin curators are aware.

**Comment by balhoff** [comment]
One thought—I realized perhaps we can stick with some high level bridges and forgo the full Uberon mapping. I think @vanaukenk and @cmungall have actually talked about this before; one small blocker was just deciding where to maintain these. Should a ZFA-to-CARO bridge live in the Uberon repo? Or, I could start adding these to the CARO repo.

**Comment by vanaukenk** [comment]
@balhoff  - some high-level bridges might be enough for now.  I don't have an opinion on where they should live, though, but @cmungall may.

**Pull request merged**
