### PR TITLE
aligning with reactome conversion

### PR DESCRIPTION
**Pull request by goodb**
@vanaukenk please have a look at these changes.  If they aren't acceptable, then we will need to change the reactome conversion accordingly.

### CODE REVIEW

**Comment by goodb** [comment]
Build is failing now because we have a test should-fail file that uses provides-direct-input-for to link a MF to a BP.  If that isn't allowed, then we will need to reconsider how we are currently modeling transport reactions from Reactome as this ends up happening a lot.  
Ping @ukemi 
related to https://github.com/geneontology/pathways2GO/issues/75

**Comment by deustp01** [comment]
In Reactome, any event instance (reaction or pathway) may legally be asserted to precede any other reaction or pathway instance. What we should do (legacy cleanup, alas) is, wherever a pathway event is involved in one of those assertions, identify the specific reaction in the upstream pathway that generates the entity that is input for the relevant reaction in the downstream pathway, and re-do the annotation to link the upstream reaction to the downstream reaction (so the two pathways are still implicitly linked).

A list of all preceding-following event pairs where one or both of the events are pathways would be a helpful start for the cleanup.

**Comment by goodb** [comment]
@deustp01 in this case, its not the pathway-as-upstream-event problem.  As things stand (on the ever-moving table), when transport reactions (without any manual GO curation in Reactome) are detected, the conversion generates nodes with type Transport.  Transport is under the BP branch of the GO.  Often, the 'provides_direct_input_for' rule is also triggered and this results in a chain of MF provides direct input for BP which fails the shex validation.

**Comment by ukemi** [comment]
Wow, this is an interesting wrinkle. I'm not sure why it didn't creep up when we were using establishment of localization. It seems to me that in this case and we are going to allow MFs to causally connect to BPs within a given model (which @thomaspd already approved), then we should allow for causal chains where the MF provides_direct_input_for the immediately downstream BP and that BP is allowed to have an output that is a provides_direct_input_for the next MF or BP in the causal chain. @deustp01, @goodb does this make sense to you? Would also like to get @vanaukenk 's thoughts, but she is out until after the holidays. 
I think we will require this to accommodate for @thomaspd 's 'coordinated processes' ( which by the way are analogous to some of Reactomes 'black box reactions' in models) in the more global GO-CAM world.

**Comment by ukemi** [comment]
PS. Again would like input from @vanaukenk, but I think transport should be broadened to include generic genes (which are a stand-in for gene products), chemicals and even cellular anatomical structures. I can't think of a gross anatomical structure off the top of my head but wouldn't be surprised if some day we come up with one.

**Comment by goodb** [comment]
@ukemi Probably didn't come to our attention before because we didn't have the shex system running - not problem either way as far as the OWL is concerned.

**Comment by goodb** [comment]
@ukemi whenever we introduce a BP, we have the same issue with the negatively_regulates and positively_regulates relations.  E.g. the following conversion is inconsistent with the current shex schema.  

Screen Shot 2019-12-19 at 9 58 53 AM
from R-HSA-3371527
Screen Shot 2019-12-19 at 9 59 43 AM

**Comment by ukemi** [comment]
This one includes a 'black box' process. I can wave my hands ans say that this is ok because if we assert that an MF regulates a BP, it means that the MF have a direct regulatory role of one of the MFs that is part of the BP. But agin, we should run this past @thomaspd and @vanaukenk to be sure that it complies with the general GO-CAM philosophy.

**Comment by ukemi** [comment]
I think @vanaukenk was leaning against allowing this because we had decided that in order to use a regulates relationship between two occurrents, we needed to know the mechanism of regulation. This would keep curators from promiscuously using regulates as a fuzzy relation as they had done in the past. But do we want to allow it in these special cases? If not we would have to convert to 'causally upstream of, positive/negative effect'.

**Comment by deustp01** [comment]
OK - entirely different issue, sorry. But the list of Reactome event instances causing problems here would still be useful because, as it turns out, we have actually done a very limited job of linking transport reactions to reactions that consume the cargo once it arrives at its new location so this would be a useful piece of cleanup and maybe easy to implement especially if the check generates a list of candidiate downstream pathways for each problem transport reaction..

**Comment by ukemi** [comment]
But @deustp01, I don't think the problem here is because the molecule changes. I think it's because the rules as we have them do not allow for any MF to provide a direct input to a BP. We wouldn't infer this relation if the entity weren't the same. I'm not sure what would happen in the cases you mention above.
But on the same entirely different thread, and not to be discussed here because it would hijack this ticket. In the future what do we do about cases like in E coli where glucose goes in one side of the membrane and comes out the other side as G6P? Is it still glucose transport? Our rules wouldn't catch that.

**Comment by ukemi** [comment]
Now second guessing my last comment. Am I correct @goodb?

**Comment by goodb** [comment]
@ukemi you are correct.  the conflict here is with a schema constraint that disallows
 MF provides_input/regulates BP relations.

**Comment by deustp01** [comment]
Hmm. Early in this thread I said

> In Reactome, any event instance (reaction or pathway) may legally be asserted to precede any other reaction or pathway instance. What we should do (legacy cleanup, alas) is, wherever a pathway event is involved in one of those assertions, identify the specific reaction in the upstream pathway that generates the entity that is input for the relevant reaction in the downstream pathway, and re-do the annotation to link the upstream reaction to the downstream reaction (so the two pathways are still implicitly linked).

and Ben replied

> in this case, its not the pathway-as-upstream-event problem. As things stand (on the ever-moving table), when transport reactions (without any manual GO curation in Reactome) are detected, the conversion generates nodes with type Transport.

But now it looks like we're back to the illegality of causal links from function to process, so I guess there are a couple of issues intertwined here. On the function-to-process links piece, yes, we do that; no, we shouldn't do that (or other links that cross function - process boundaries); and this might be a good occasion to start a clean-up.

**Comment by goodb** [comment]
this has been replaced by another PR.

**Pull request closed without merging**
