### PR TITLE
Replace obsolete native cell with cell

### PR DESCRIPTION
**Pull request by balhoff**
CL has obsoleted 'native cell'.

### CODE REVIEW

**Review by vanaukenk — COMMENTED** [review]
@balhoff 
We have other places in the ShEx where we refer to NativeCell, e.g. CellDivision and CellFateCommitment shapes.
We will need to update those, as well.

**Comment by balhoff** [comment]
> @balhoff We have other places in the ShEx where we refer to NativeCell, e.g. CellDivision and CellFateCommitment shapes. We will need to update those, as well.

Not sure why I missed those! I was searching in the Github UI and for some reason didn't see them.

**Comment by balhoff** [comment]
Thanks for catching that @vanaukenk, I think I got it now.

**Comment by balhoff** [comment]
@vanaukenk the CI is failing because we have an instance of [calcium oxalate](http://purl.obolibrary.org/obo/CHEBI_60579) in this test model: https://github.com/geneontology/go-shapes/blob/master/test_ttl/go_cams/should_pass/Test027-has_input_2_MolecularEntity.ttl. Apparently this CHEBI term is not in any of our imports. Not sure why it passed before—maybe at some point we were importing the entire CHEBI?

I could just replace the CHEBI term with another. Does that sound reasonable?

**Comment by balhoff** [comment]
> I could just replace the CHEBI term with another. Does that sound reasonable?

This is what I did, and tests are passing.

**Comment by vanaukenk** [comment]
Thanks @balhoff 
I've been on calls most of the afternoon, so sorry I missed this earlier.

**Pull request merged**
