### PR TITLE
Create WIP_standard_annot_ShEx

### PR DESCRIPTION
**Pull request by vanaukenk**
First draft of standard annotation ShEx

### CODE REVIEW

**Comment by vanaukenk** [comment]
@kltm - right now, no.

**Comment by vanaukenk** [comment]
See: https://github.com/geneontology/noctua-standard-annotations/issues/9

**Comment by kltm** [comment]
(Sorry to bug--thank you!)

**Comment by vanaukenk** [comment]
A well deserved nudge, I think :-)

**Pull request merged**
