### PR TITLE
Local reasoner for superclasses

### PR DESCRIPTION
**Pull request by goodb**
this is a reasoner validation code change.  no change to shex or to the test models.

### CODE REVIEW

**Comment by goodb** [comment]
@balhoff travis runs out of memory if trying to load go-lego locally.  Do you know how to give it more?

**Comment by balhoff** [comment]
Let's see what happens if we set the `mvn` heap size: cde4b7b075dbb9b1ae1dcaf2a6c4fef1b7949025

**Comment by balhoff** [comment]
Looks like now the problems is it's taking too long to download go-lego.

**Comment by goodb** [comment]
Seems a little odd.  It timed out after ten minutes complaining about a lack of output.  Doesn't take that long here for me and my connection isn't that great.  

I wonder if we could either increase that timeout or provide some output while its working to keep it running.

**Comment by goodb** [comment]
@balhoff setting the memory in the maven surefire plugin seems to work.  The branch build is failing correctly because of the ZDB gene identifier problem discussed last week.  This is cured in master hence the pull is passing.  I'm going to hesitantly make the merge here.  We are right on the threshold of the default memory available to travis with this set up and I worry about stability..  Its easy to switch back to the sparql based system if we need to.

**Pull request merged**
