### PR TITLE
fixing AnnotatedEdge, adding a basic GoRule06 violations check

### PR DESCRIPTION
**Pull request by dougli1sqrd**
This makes a basic GoRule06 shape, and some test Turtle. I'd like to be able to move the future set of GoRules into a different file, but not totally sure how to perform that import yet.

### CODE REVIEW

**Comment by pgaudet** [comment]
Please use the correct labels for the rule: 
https://github.com/geneontology/go-site/blob/master/metadata/rules/gorule-0000006.md

**GORULE:0000006**


Not 'GoRule06'.

Thanks, Pascale

**Comment by dougli1sqrd** [comment]
@goodb @balhoff So the tests look they are failing because test2-enriched.ttl has a an Axiom triple without evidence. Do we want to make evidence required? Should we turn off the AnnotatedEdge Shape? Should we add evidence to the triples?
```
[  a                      owl:Axiom ;
  dc:contributor         "http://orcid.org/0000-0002-7334-7852" ;
  dc:date                "2019-07-09" ;
  <http://purl.org/pav/providedBy>
          "http://geneontology.org" ;
  owl:annotatedProperty  <http://purl.obolibrary.org/obo/BFO_0000050> ;
  owl:annotatedSource    <http://model.geneontology.org/59dc728000000510/5ce58dde00002096> ;
  owl:annotatedTarget    <http://model.geneontology.org/59dc728000000510/5ce58dde00002086>  
] .
```

**Comment by goodb** [comment]
@dougli1sqrd this is cool.  It brings up some important questions about how we want the gorules work to integrate here.  For one thing, this introduces a new pattern into the schema.  So far everything is done with positive matches in mind - this is the first shape in there that should not be matched unless something is wrong.  I think that is probably sensible, but will likely impact code that expects otherwise (like what I am working on for minerva).  

1. Should we put these kinds of shapes in a separate file that imports the main schema?  
2. Are there gorules that should be applied to go-cams that can't be handled with shex?  

You might also need to check on cardinality in your shape.  Axioms can have multiple references.  I believe there is another example in the same ttl file with 2 refs.  

To answer your question, I think it would be correct to flag assertions with no evidence.  I think that is definitely a violation that should be caught.  (Though the UI shouldn't be too pushy about it while people are actively editing.)

**Comment by goodb** [comment]
@dougli1sqrd let me know what you are thinking here with regard to your go rules implementation strategy.

**Comment by dougli1sqrd** [comment]
Yeah I definitely think we should try and put the GO Rule shapes into a different file. I just haven't experimented with importing other shape files. 

I'm not sure if there are some rules that _can't_ be done with shex, but I feel like doing my one example it shows that they can be a little awkward. Perhaps in some ways sparql could be easier for some rules? 

You mean the axiom can have multiple evidence triples? 

I can add the missing evidence in the turtle that should pass then.

Thanks!

**Pull request closed without merging**
