### PR TITLE
Opinions on regex symbols vs. digits?

### PR DESCRIPTION
**Pull request by balhoff**
This PR is just to see what people think about adopting regex symbols (probably more typical ShEx style) for relation cardinalities. I noticed that every cardinality in our doc was either `{1}` (which is the standard, no specifier) or `{0,1}` (which can be written regex-style as `?`).

I kind of favor going the ShExier way and embracing the default and `?`, but perhaps other prefer the digits?

### CODE REVIEW

**Comment by pgaudet** [comment]
I must say for me it is not clear that  {?} means {0,1}; I would have guessed it is undefined, if you didn't say it had a meaning; but if it is a defined values, I would interpret it as {0,n}

Pascale

**Comment by vanaukenk** [comment]
@balhoff 
Would you like more discussion of this, or are you okay with sticking to the {0,1} expression that we are using?

**Comment by balhoff** [comment]
I'm okay with being more explicit.

**Comment by vanaukenk** [comment]
Okay, thanks @balhoff .
Then we will leave the {0, 1} expressions as is.

**Pull request closed without merging**
