### PR TITLE
Contributor is required; date is singular/required

### PR DESCRIPTION
**Pull request by kltm**
Update individuals. contributor is required; date is singular/required.

Tagging @ukemi @vanaukenk @goodb @dustine32

### CODE REVIEW

**Comment by balhoff** [comment]
@kltm I resolved conflicts on this PR. Do we want to merge this change now?

**Comment by kltm** [comment]
Double checking with @dustine32 , but I think there is no consequence to this change as we are not actively using ShEx in daily operations?

**Comment by kltm** [comment]
If there is no consequence, it's free to be merged at will.

**Comment by dustine32** [comment]
@kltm I've been running ShEx for Reactome and YeastPathways loads but certainly not daily. I think this is good to merge since both of these model sets should have some contributor and date set on every individual and edge. So, if this change causes those models to fail, that's a good thing!

**Pull request merged**
